In [2]:
import pandas as pd
import numpy as np

In [12]:
dict1 = {
    "Name" :["John", "Tarun", "Amit", "Ravi"],
    "Age" :[23, 25, 26, 30],
    "City" :["New York", "Los Angeles", "Chicago", "Houston"],
    "Salary" :[70000, 80000, 75000, 90000],
    "skills" :["Python", "Java", "C++", "JavaScript"]
}
df = pd.DataFrame(dict1)
df

    Name  Age         City  Salary      skills
0   John   23     New York   70000      Python
1  Tarun   25  Los Angeles   80000        Java
2   Amit   26      Chicago   75000         C++
3   Ravi   30      Houston   90000  JavaScript

In [4]:
df.head(2) # Display the first two rows of the DataFrame

    Name  Age         City  Salary  skills
0   John   23     New York   70000  Python
1  Tarun   25  Los Angeles   80000    Java

In [5]:
df.tail(2) # Display the last two rows of the DataFrame

   Name  Age     City  Salary      skills
2  Amit   26  Chicago   75000         C++
3  Ravi   30  Houston   90000  JavaScript

In [6]:
df.describe() # Get a statistical summary of the DataFrame

            Age        Salary
count   4.00000      4.000000
mean   26.00000  78750.000000
std     2.94392   8539.125638
min    23.00000  70000.000000
25%    24.50000  73750.000000
50%    25.50000  77500.000000
75%    27.00000  82500.000000
max    30.00000  90000.000000

In [7]:
Tarun = pd.read_csv("Tarun.csv")
Tarun

    Name  Age         City  Salary      skills
0   Ajay   86        Delhi   70000      Python
1  Tarun   25  Los Angeles   80000        Java
2   Amit   26      Chicago   75000         C++
3   Ravi   30      Houston   90000  JavaScript

In [ ]:
import pandas as pd
dict1 = {
    "Name" :["John", "Tarun", "Amit", "Ravi"],
    "Age" :[23, 25, 26, 30],
    "City" :["New York", "Los Angeles", "Chicago", "Houston"],
    "Salary" :[70000, 80000, 75000, 90000],
    "skills" :["Python", "Java", "C++", "JavaScript"]
}
s = pd.Series(dict1)
print(s)

Name                      [John, Tarun, Amit, Ravi]
Age                                [23, 25, 26, 30]
City      [New York, Los Angeles, Chicago, Houston]
Salary                 [70000, 80000, 75000, 90000]
skills              [Python, Java, C++, JavaScript]
dtype: object